### PR TITLE
TestNow

### PR DESCRIPTION
**Pull request by relentless-pursuit**

### CODE REVIEW

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by relentless-pursuit** [comment]
trigger action

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters6.java

**Comment by romani** [comment]
Github, generate report for PackageAnnotation/all-examples-in-one

**Comment by romani** [comment]
@relentless-pursuit , let use this PR to testing of https://github.com/checkstyle/test-configs/issues/120

CI is too overloaded in checkstyle org, so it takes a long queue to job to finish

**Comment by relentless-pursuit** [comment]
@romani, this isn't the right PR
because, it is created differently

**Comment by relentless-pursuit** [comment]
> @romani, this isn't the right PR because, it is created differently

it is created via checktyle-gsoc, not forked from checkstyle

**Comment by relentless-pursuit** [comment]
let me create a new PR for you to test

**Pull request closed without merging**
