### PR TITLE
Secondary PR

### PR DESCRIPTION
**Pull request by relentless-pursuit**
This PR is meant for rapid iteration for self-use.

### CODE REVIEW

**Comment by relentless-pursuit** [comment]
check:AnnotationLocation

**Comment by relentless-pursuit** [comment]
check:AnnotationLocation

**Comment by relentless-pursuit** [comment]
check:AnnotationLocation

**Comment by relentless-pursuit** [comment]
Perform regression testing for config1

**Comment by relentless-pursuit** [comment]
Perform regression testing for config1 for AnnotationLocation

**Comment by relentless-pursuit** [comment]
Perform regression testing for config1 for AnnotationLocation

**Comment by relentless-pursuit** [comment]
Perform regression testings for config1 for AnnotationLocation

**Comment by relentless-pursuit** [comment]
Perform regression testings for config1 for AnnotationLocation

**Comment by relentless-pursuit** [comment]
Perform regression testings for config1 for AnnotationLocation

**Comment by relentless-pursuit** [comment]
Perform regression testings for config1 for AnnotationLocation

**Comment by relentless-pursuit** [comment]
check:AnnotationLocation

**Comment by relentless-pursuit** [comment]
Perform regression testings for config1 for AnnotationLocation

**Comment by relentless-pursuit** [comment]
Perform regression testings for config1 for AnnotationLocation

**Comment by relentless-pursuit** [comment]
Perform regression testings for config1 for AnnotationLocation

**Comment by relentless-pursuit** [comment]
Perform regression testings for config1 for AnnotationLocation

**Comment by relentless-pursuit** [comment]
generate test-config/AnnotationLocation/Example1

**Comment by relentless-pursuit** [comment]
generate test-config/AnnotationLocation/Example1

**Comment by relentless-pursuit** [comment]
generate test-config/AnnotationLocation/Example1

**Comment by relentless-pursuit** [comment]
generate test-config/AnnotationLocation/Example1

**Comment by relentless-pursuit** [comment]
generate test-config/AnnotationLocation/Example1

**Comment by relentless-pursuit** [comment]
generate test-config/AnnotationLocation/Example1

**Comment by relentless-pursuit** [comment]
generate test-config/AnnotationLocation/Example1

**Comment by relentless-pursuit** [comment]
generate test-config/AnnotationLocation/Example1

**Comment by relentless-pursuit** [comment]
generate test-config/AnnotationLocation/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example2

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example2

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example2

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example2

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example2

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example2

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example2

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example2

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example2

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example2

**Comment by relentless-pursuit** [comment]
Github, generate report

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example2

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example2

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
> https://chesktyler-reports.s3.ap-south-1.amazonaws.com/ebeea5a_2024234416/reports/diff/index.html

@Romani here.

**Comment by romani** [comment]
nice, please send PR to main repo.

**Comment by relentless-pursuit** [comment]
Github, generate report AnnotationLocation/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report for AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report for AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report for AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report for AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report for AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report for AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report for AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report for AnnotationUseStyling/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report for AnnotationUseStyling/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report for AnnotationUseStyling/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report for AnnotationUseStyling/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report for AnnotationUseStyling/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report for AnnotationUseStyle/Example1

**Comment by relentless-pursuit** [comment]
Github, generate report for AnnotationUseStyling/Example3

**Comment by relentless-pursuit** [comment]
Github, generate report for AnnotationUseStyle/Example3

**Comment by relentless-pursuit** [comment]
Github, generate report for SummaryJavadoc/Example1

**Pull request closed without merging**
