### PR TITLE
Test all-in-one from bottom to top

### PR DESCRIPTION
**Pull request by romani**
I am going from bottom to top

https://github.com/checkstyle/test-configs

https://github.com/checkstyle/test-configs/issues/120#issuecomment-2241202788

### CODE REVIEW

**Comment by romani** [comment]
Github, generate report for WriteTag/all-examples-in-one

**Comment by romani** [comment]
This PR was created from phone.
So, it is convenient.

**Comment by romani** [comment]
Github, generate report for WhitespaceAround/all-examples-in-one

**Comment by romani** [comment]
@relentless-pursuit, why it didn't trigger?

**Comment by relentless-pursuit** [comment]
> @relentless-pursuit, why it didn't trigger?

```
Error:  Java heap space -> [Help 1]
java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf (Arrays.java:3745)
    at java.lang.AbstractStringBuilder.ensureCapacityInternal (AbstractStringBuilder.java:172)
    at java.lang.AbstractStringBuilder.append (AbstractStringBuilder.java:633)
    at java.lang.StringBuffer.append (StringBuffer.java:397)
    at java.io.StringWriter.write (StringWriter.java:122)
    at java.io.PrintWriter.write (PrintWriter.java:542)
    at java.io.PrintWriter.write (PrintWriter.java:559)
    at org.apache.maven.doxia.sink.XhtmlBaseSink.write (XhtmlBaseSink.java:2110)
    at org.apache.maven.doxia.siterenderer.sink.SiteRendererSink.write (SiteRendererSink.java:337)
    at org.apache.maven.doxia.sink.XhtmlBaseSink.table_ (XhtmlBaseSink.java:1258)
    at org.apache.maven.plugins.checkstyle.CheckstyleReportGenerator.doDetails (CheckstyleReportGenerator.java:629)
    at org.apache.maven.plugins.checkstyle.CheckstyleReportGenerator.generateReport (CheckstyleReportGenerator.java:152)
    at org.apache.maven.plugins.checkstyle.AbstractCheckstyleReport.generateMainReport (AbstractCheckstyleReport.java:780)
    at org.apache.maven.plugins.checkstyle.AbstractCheckstyleReport.executeReport (AbstractCheckstyleReport.java:537)
    at org.apache.maven.plugins.checkstyle.CheckstyleReport.executeReport (CheckstyleReport.java:57)
    at org.apache.maven.reporting.AbstractMavenReport.generate (AbstractMavenReport.java:255)
    at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument (ReportDocumentRenderer.java:219)
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule (DefaultSiteRenderer.java:319)
    at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render (DefaultSiteRenderer.java:135)
    at org.apache.maven.plugins.site.SiteMojo.renderLocale (SiteMojo.java:175)
    at org.apache.maven.plugins.site.SiteMojo.execute (SiteMojo.java:138)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:299)
Error:  
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/OutOfMemoryError
Caught: groovy.lang.GroovyRuntimeException: Error: !
groovy.lang.GroovyRuntimeException: Error: !
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at diff.executeCmd(diff.groovy:736)
	at diff.executeCmd(diff.groovy:729)
	at diff$executeCmd$16.callCurrent(Unknown Source)
	at diff.runMavenExecution(diff.groovy:701)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at diff$_generateCheckstyleReport_closure4.doCall(diff.groovy:304)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at diff.generateCheckstyleReport(diff.groovy:273)
	at diff$generateCheckstyleReport$10.callCurrent(Unknown Source)
	at diff.launchCheckstyleReport(diff.groovy:233)
	at diff$launchCheckstyleReport$6.callCurrent(Unknown Source)
	at diff.run(diff.groovy:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error: Process completed with exit code 1.
```

**Comment by relentless-pursuit** [comment]
> @relentless-pursuit, why it didn't trigger?

It complains OOM

**Comment by romani** [comment]
Github, generate report for WhitespaceAfter/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for VisibilityModifier/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for VariableDeclarationUsageDistance/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for UpperEll/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for UnusedLocalVariable/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for UnusedImports/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for UnnecessarySemicolonInTryWithResources/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for UnnecessarySemicolonInEnumeration/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for UnnecessarySemicolonAfterTypeMemberDeclaration/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for UnnecessarySemicolonAfterOuterTypeDeclaration/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for UnnecessaryParentheses/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for UnnecessaryParentheses/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for UncommentedMain/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for TypecastParenPad/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for TypeName/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for Translation/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for TrailingComment/all-examples-in-one

**Comment by romani** [comment]
Trailing comments is timeouted https://github.com/checkstyle-gsoc/checkstyle/actions/runs/10105466649/job/27945999431

**Comment by romani** [comment]
Github, generate report for ThrowsCount/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for TodoComment/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for SuppressWarnings/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for SuperFinalize/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for SuperClone/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for SummaryJavadoc/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for StringLiteralEquality/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for StringLiteralEquality/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for StaticVariableName/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for SingleSpaceSeparator/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for SingleLineJavadoc/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for SimplifyBooleanReturn/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for SimplifyBooleanReturn/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for SeparatorWrap/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for RightCurly/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for ReturnCount/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for RequireThis/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for RequireEmptyLineBeforeBlockTagGroup/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for RegexpSinglelineJava/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for RegexpSinglelineJava/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for RegexpSinglelineJava/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for RegexpSinglelineJava/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for RegexpSingleline/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for RegexpOnFilename/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for RegexpMultiline/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for RegexpHeader/all-examples-in-one

**Pull request closed without merging**
