### PR TITLE
Official Testing of regression-report.yml

### PR DESCRIPTION
**Pull request by relentless-pursuit**
Diff Regression config: https://gist.githubusercontent.com/Zopsss/eef363a452104d034a9ce7be532f647d/raw/01ec2b9c4cd7afd4fb508acccf1605b57767edc0/master_google_checks.xml

Diff Regression patch config: https://gist.githubusercontent.com/Zopsss/40bbda26eff022ac495900de8931e9d9/raw/2d55e2a6fb2003129b89a86007d245c6c25d74f2/protected_methods_google_checks.xml

Diff Regression projects: https://gist.githubusercontent.com/Zopsss/9960953f88e763d31eea3a14447b861f/raw/edfd96ea7a5757cea2e08856be98776cbb21a171/guava-project.properties

### CODE REVIEW

**Comment by relentless-pursuit** [comment]
@Romani, you can use this PR.

**Comment by romani** [comment]
Github, generate report for PackageAnnotation/all-examples-in-one

**Comment by relentless-pursuit** [comment]
The report failed because i had not used AWS config credentials and using that of checkstyle. I have made changes and added my own AWS S3 credentials.

**Comment by relentless-pursuit** [comment]
Github, generate report for PackageAnnotation/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for OverloadMethodsDeclarationOrder/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for OuterTypeNumber/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Updated the changes for lable.

**Comment by relentless-pursuit** [comment]
Github, generate report for IllegalIdentifierName/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for OrderedProperties/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/test/resources/com/puppycrawl/tools/checkstyle/checks/finalparameters/InputFinalParameters1.java

**Comment by relentless-pursuit** [comment]
Github, generate report by config from InputFinalParameters4.java

**Comment by relentless-pursuit** [comment]
jar trigger InputFinalParameters4.java

**Comment by romani** [comment]
Github, generate report for OperatorWrap/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for OneTopLevelClass/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for OneStatementPerLine/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for NonEmptyAtclauseDescription/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for NoWhitespaceBeforeCaseDefaultColon/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for NoWhitespaceBefore/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for NoWhitespaceAfter/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for NoLineWrap/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for NoFinalizer/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for NoEnumTrailingComma/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for NoCodeInFile/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for NoClone/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for NoArrayTrailingComma/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for NewlineAtEndOfFile/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for NestedTryDepth/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for NestedIfDepth/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for NestedForDepth/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for NPathComplexity/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MutableException/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MultipleVariableDeclarations/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MultipleStringLiterals/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for ModifierOrder/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MultipleStringLiterals/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for ModifierOrder/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for ModifiedControlVariable/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MissingSwitchDefault/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MissingOverride/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MissingJavadocType/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MissingJavadocPackage/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MissingJavadocPackage/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MissingJavadocMethod/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MissingDeprecated/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MissingCtor/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MethodTypeParameterName/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MethodParamPad/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MethodName/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MethodLength/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MethodCount/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MemberName/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MatchXpath/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for MagicNumber/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for LocalVariableName/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for LocalFinalVariableName/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for LineLength/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for LeftCurly/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report for RightCurly/all-examples-in-one

**Comment by relentless-pursuit** [comment]
@Romani, i have modified the workflow to test the jar running. I tested and it works fine for 2 examples. We can test more on it. And, this is how the test report looks like for now. I know the names are changed, i will change them when i raise a PR for DiffTools.java

https://github.com/checkstyle-gsoc/checkstyle/pull/29#issuecomment-2345007427

image

**Comment by romani** [comment]
Github, generate report for LambdaParameterName/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for LambdaBodyLength/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for JavadocVariable/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for JavadocType/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for JavadocTagContinuationIndentation/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for JavadocStyle/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for JavadocParagraph/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for JavadocPackage/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for JavadocMissingWhitespaceAfterAsterisk/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for JavadocMissingLeadingAsterisk/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for JavadocMethod/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report for ReturnCount/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for JavadocLeadingAsteriskAlign/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for JavadocContentLocation/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for JavadocBlockTagLocation/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for JavaNCSS/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for InvalidJavadocPosition/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for Indentation/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for InterfaceTypeParameterName/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for InterfaceMemberImpliedModifier/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for InterfaceIsType/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for InnerTypeLast/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for InnerAssignment/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for JavadocStyle/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for IllegalInstantiation/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for IllegalImport/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for ImportOrder/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for IllegalType/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for IllegalTokenText/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for IllegalToken/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for IllegalThrows/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for IllegalCatch/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for HideUtilityClassConstructor/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for HiddenField/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for Header/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for GenericWhitespace/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for FinalParameters/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for FinalLocalVariable/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for FinalClass/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for FileTabCharacter/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for FileLength/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for FallThrough/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for ExplicitInitialization/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for ExecutableStatementCount/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for EqualsHashCode/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for EqualsHashCode/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for EqualsAvoidNull/all-examples-in-one

**Comment by romani** [comment]
Github, generate report for EmptyStatement/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report for EmptyStatement/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report for EqualsAvoidNull/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report for FallThrough/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/todocomment/Example1.java

**Comment by relentless-pursuit** [comment]
> Github, generate report by config from src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/todocomment/Example1.java

https://github.com/checkstyle-gsoc/checkstyle/actions/runs/10891869538

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/todocomment/Example1.java

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/todocomment/Example1.java

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/todocomment/Example1.java

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/todocomment/Example1.java

**Comment by relentless-pursuit** [comment]
Github, generate report for EmptyStatement/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/todocomment/Example1.java

**Comment by relentless-pursuit** [comment]
GitHub, generate report for configs in PR description

**Comment by relentless-pursuit** [comment]
Tesgting for the PR starts from here, i had to update the AWS credentials for the report generation.

**Comment by relentless-pursuit** [comment]
GitHub, generate report for configs in PR description

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/todocomment/Example1.java

**Comment by relentless-pursuit** [comment]
Github, generate report for EmptyStatement/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report for OuterTypeNumber/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/todocomment/Example1.java

**Comment by relentless-pursuit** [comment]
Github, generate report for ParenPad/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report for ParenPad/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report for configs in PR description

**Comment by relentless-pursuit** [comment]
Github, generate report for PatternVariableName/all-examples-in-one

**Comment by relentless-pursuit** [comment]
Github, generate report by config from src/xdocs-examples/resources/com/puppycrawl/tools/checkstyle/checks/todocomment/Example1.java

**Comment by relentless-pursuit** [comment]
Github, generate report for configs in PR description

**Comment by relentless-pursuit** [comment]
Github, generate report for configs in PR description

**Comment by romani** [comment]
@relentless-pursuit, this PR is unmanageable, please close it and create new PR, we will finish testing in new PR.

**Pull request closed without merging**
